version: "3.7"

services:
  glue:
    image: glue-local:3
    depends_on:
      - s3
    build:
      context: .
      dockerfile: glue.dockerfile
    environment:
      AWS_ACCESS_KEY_ID: foobar
      AWS_SECRET_ACCESS_KEY: foobarfoo

  s3:
    hostname: s3
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    environment:
      MINIO_ACCESS_KEY: foobar
      MINIO_SECRET_KEY: foobarfoo
    ports:
      - "9000"
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: server /data
